### ISSUE TITLE
Interaktive Kreaturenanzeige

### ISSUE THREAD

**Issue by XaverStiensmeier** [Ilaris-Tools/ilaris-online.de#25]
Wäre cool, wenn man bei Kreaturen auf AT, VT und TP würfeln könnte und Waffeneigenschaften, Kreaturenvorteile, ... anklicken könnte.

Muss keine VTT ersetzen, aber das Würfelbar-machen für AT, VT und TP dürfte reletiv gut machbar sein.

**Comment by lukruh** [comment]
AT, VT, TP und MR können jetzt gewürfelt werden. Die Zusatzinfos von Vorteilen und Waffeneigenschaften, hab ich auch schon angedacht, aber dazu müssten sie erstmal mit der Regeldatenbank verknüpft werden. Bisher sind nur die Eigenschaften anklickbar, weil dazu alle Infos mit in der Kreatur stecken.
